name: CI (Jira cloud example with GH action)

on: [push]

jobs:
  build:
    name: UI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Execute tests with Maven
        run: mvn clean test -Dlogin=${{ secrets.login }} -Dpassword=${{ secrets.password }}

      - name: Submit results to Xray
        uses: mikepenz/xray-action@v2.4.5
        run: |
          echo ##########
          ls /home/runner/work/poc-ui-xray/poc-ui-xray/target/surefire-reports/
          ls /home/runner/work/poc-ui-xray/poc-ui-xray

        with:
          username: ${{ secrets.client_id }}
          password: ${{ secrets.client_secret }}
          testFormat: "junit"
          testPaths: "**/surefire-reports/TEST-junit-jupiter.xml"
          projectKey: "QAT"
          testPlanKey: "QAT-39"